In [87]:
import os
os.makedirs('data', exist_ok=True)
import urllib.request
urllib.request.urlretrieve(
    'https://raw.githubusercontent.com/mendiolaleonel2002-debug/analisis_exploratorio/main/data/datos_delitos.csv',
    'data/datos_delitos.csv'
)

('data/datos_delitos.csv', <http.client.HTTPMessage at 0x7aba5f7a6000>)

# Limpieza de datos

La mayoría de la gente piensa que ser científico de datos significa estar corriendo modelos avanzados de Machine Learning todo el tiempo. La realidad es muy distinta:

![Tiempo de un científico de datos](https://github.com/bryan2512004-oss/analisis_exploratorio/blob/main/img/datascientist_time.jpeg?raw=1)

La gran mayoría del tiempo se va **limpiando y organizando** los datos con los que queremos trabajar.

Los científicos de datos utilizamos herramientas como Pandas, Numpy, Matplotlib y Seaborn para limpiar los datos con los que queremos hacer algo.

## ETL

Un tipo de tarea que realizamos con gran frecuencia los científicos de datos son los **ETL**.

![Proceso de ETL](https://github.com/bryan2512004-oss/analisis_exploratorio/blob/main/img/etl.png?raw=1)

ETL es un acrónimo que significa Extract, Transform, Load. Es un proceso que se utiliza para extraer datos de una fuente, transformarlos en un formato que sea adecuado para el análisis y cargarlos en una base de datos o algún otro sistema de almacenamiento.

## Ejemplo práctico

Los datos que usaremos para esta limpieza y nuestro siguiente análisis son datos de incidencia delictiva en nuestro país.

La iniciativa de datos abiertos del gobierno de México nos proporciona datos de incidencia delictiva desde 2015 hasta la fecha. Los datos se actualizan todos los meses y se pueden descargar desde el siguiente enlace: https://www.gob.mx/sesnsp/acciones-y-programas/datos-abiertos-de-incidencia-delictiva

---

Como podemos ver en el portal, se proporcionan los datos tanto a nivel estatal como a nivel municipal. En este caso, utilizaremos los datos a nivel estatal.

Descarguemos los datos y guardemos el archivo CSV en la carpeta data con el nombre `datos_delitos.csv`.

---

Ahora leamos el archivo CSV y veamos cómo se ven los datos.

Primero que nada, importemos pandas

In [88]:
import pandas as pd

In [89]:
url = 'https://raw.githubusercontent.com/mendiolaleonel2002-debug/analisis_exploratorio/main/data/datos_delitos.csv'
df = pd.read_csv(url, encoding='ISO-8859-1')

Aquí tenemos un error muy común que suele ocurrir cuando un archivo se guarda en una computadora con cierto "encoding".

Un encoding es una tabla que relaciona un número con un carácter. Por ejemplo, en la tabla ASCII, el número 65 corresponde a la letra "A".

Si el archivo que estamos leyendo fue guardado con un encoding distinto al que pandas espera, nos arrojará un error.

Para solucionar esto, podemos utilizar el parámetro `encoding` de la función `pd.read_csv()` y especificar el encoding correcto.

¿Pero cómo sabemos con qué encoding cuenta el archivo?

La realidad es que la gran mayoría de los archivos los encontrarán en encoding utf-8 y Pandas no va a dar ningún error. Aquí estamos teniendo este problema porque la computadora que utilizan para generar este archivo uso un encoding diferente a utf-8.

En México, por lo general, si un archivo no está en utf-8, lo más seguro es que esté en `ISO-8859-1` o `latin1`.

Intentemos cargar el archivo especificando el encoding `ISO-8859-1`.

In [90]:
url = 'https://raw.githubusercontent.com/mendiolaleonel2002-debug/analisis_exploratorio/main/data/datos_delitos.csv'
df = pd.read_csv(url, encoding='ISO-8859-1')
df.head()

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0.0,1.0,2.0,0.0,0.0,0.0
3,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2,0,0,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0,0,0,0,1,0,0.0,0.0,0.0,0.0,0.0,0.0

Y vemos que ya podemos leer correctamente el archivo.


¿Existe alguna forma de verificar el encoding de un archivo sin tener que estar adivinando?

ChatGTP generó el siguiente código:

In [91]:
import chardet

def detect_encoding(file_path):
    with open(file_path, 'rb') as f:
        rawdata = f.read()
    result = chardet.detect(rawdata)
    return result

file_path = './data/datos_delitos.csv'
encoding_info = detect_encoding(file_path)
print(f"Detected encoding: {encoding_info['encoding']}")

Detected encoding: ISO-8859-1

In [92]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Sigamos...

In [93]:
df.tail(3)

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
31357,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,20,22,34,35,34,37,NaN,NaN,NaN,NaN,NaN,NaN
31358,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Electorales,Electorales,Electorales,0,1,0,11,31,23,NaN,NaN,NaN,NaN,NaN,NaN
31359,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Otros delitos del Fuero Común,Otros delitos del Fuero Común,Otros delitos del Fuero Común,151,183,174,199,208,177,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31360 entries, 0 to 31359
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Año                     31360 non-null  int64
 1   Clave_Ent               31360 non-null  int64
 2   Entidad                 31360 non-null  object
 3   Bien jurídico afectado  31360 non-null  object
 4   Tipo de delito          31360 non-null  object
 5   Subtipo de delito       31360 non-null  object
 6   Modalidad               31360 non-null  object
 7   Enero                   31360 non-null  int64
 8   Febrero                 31360 non-null  int64
 9   Marzo                   31360 non-null  int64
 10  Abril                   31360 non-null  int64
 11  Mayo                    31360 non-null  int64
 12  Junio                   31360 non-null  int64
 13  Julio                   28224 non-null  float64
 14  Agosto                  28224 non-null  float64
 15  Septiembre              28224 non-null  float64
 16  Octubre                 28224 non-null  float64
 17  Noviembre               28224 non-null  float64
 18  Diciembre               28224 non-null  float64
dtypes: float64(6), int64(8), object(5)
memory usage: 4.5+ MB

Bien. Están muy bien los datos. Sin embargo, tenemos un problema con el que es muy común encontrarnos.

Resulta que el formato en el que está el archivo es fácil entender por seres humanos:


```markdown
| Año      | Entidad  | Enero    | Febrero  | Mes X    |
|----------|----------|----------|----------|----------|
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
```

Vemos que tenemos los meses como encabezados. Es decir, el archivo está tratando cada mes como si fuera una variable.

Nosotros como científicos de datos estamos más interesados en conjuntos de datos que no estén en este formato de "resumen" o "tabla dinámica". Para nosotros, lo ideal sería que cada mes fuera simplemente una observación más en nuestro conjunto de datos. Es decir, queremos transformar la tabla de arriba en:

```markdown
| Año      | Entidad  | Mes        |
|----------|----------|------------|
|   ...    |   ...    |   Enero    |
|   ...    |   ...    |   Febrero  |
|   ...    |   ...    |   Marzo    |
|   ...    |   ...    |   Abril    |
|   ...    |   ...    |   Mes X    |
```

A este tipo de formato le llamos "formato largo de datos".

Haremos las siguientes limpiezas:
* Transformar los nombres de las columnas para que no tengan caracteres especiales y estén siempre en minúsculas
* Convertir el dataset a un formato de datos "largo"

In [95]:
for col in df.columns:
    print(col)

Año
Clave_Ent
Entidad
Bien jurídico afectado
Tipo de delito
Subtipo de delito
Modalidad
Enero
Febrero
Marzo
Abril
Mayo
Junio
Julio
Agosto
Septiembre
Octubre
Noviembre
Diciembre

In [96]:
len(df.columns)

19

### Limpiar nombres de columnas

In [97]:
def limpiar_columnas(df):
    columnas_limpias = []
    for col in df.columns:
        # convertir a minusculas, reemplazar espacios por guiones bajos y eliminar caracteres especiales
        col = col.lower().replace(" ", "_").replace("ñ", "ni").replace(".", "").replace("á", "a").replace("é", "e").replace("í","i").replace("ó", "o").replace("ú", "u")
        columnas_limpias.append(col)

    df.columns = columnas_limpias

    return df

In [98]:
df.head(2)

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0

In [99]:
df = limpiar_columnas(df)

In [100]:
df.head(3)

,anio,clave_ent,entidad,bien_juridico_afectado,tipo_de_delito,subtipo_de_delito,modalidad,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0.0,1.0,2.0,0.0,0.0,0.0

Muy bien. Ahora lo que queremos hacer es quitar algunas columnas. Nos interesan nada más las siguientes:

In [101]:
df[['anio', 'entidad']]

       anio         entidad
0      2015  Aguascalientes
1      2015  Aguascalientes
2      2015  Aguascalientes
3      2015  Aguascalientes
4      2015  Aguascalientes
...     ...             ...
31355  2024       Zacatecas
31356  2024       Zacatecas
31357  2024       Zacatecas
31358  2024       Zacatecas
31359  2024       Zacatecas

[31360 rows x 2 columns]

In [102]:
df = df[['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'subtipo_de_delito', 'modalidad','enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre']]
df.head(2)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,modalidad,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0

### Formato largo de datos

Ahora, usaremos el método `melt` para convertir las columnas a observaciones.

Queremos convervar las coumnas:
* anio
* clave_ent
* entidad
* tipo_de_delito
* subtipo_de_delito
* modalidad

El resto de las columnas las vamos a juntar en una nueva columna llamada "nombre_mes" y sus valores los vamos a sumar en otra llamada "frecuencia"

In [103]:
print("Shape ", df.shape)

Shape  (31360, 18)

In [104]:
datos_long = df.melt(id_vars=['anio', 'clave_ent', 'entidad','tipo_de_delito', 'subtipo_de_delito', 'modalidad'], var_name='nombre_mes', value_name='frecuencia')

In [105]:
print("Shape: ", datos_long.shape)

Shape:  (376320, 8)

In [106]:
datos_long.head(5)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,modalidad,nombre_mes,frecuencia
0,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma de fuego,enero,3.0
1,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma blanca,enero,1.0
2,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con otro elemento,enero,0.0
3,2015,1,Aguascalientes,Homicidio,Homicidio doloso,No especificado,enero,2.0
4,2015,1,Aguascalientes,Homicidio,Homicidio culposo,Con arma de fuego,enero,0.0

In [107]:
datos_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376320 entries, 0 to 376319
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   anio               376320 non-null  int64
 1   clave_ent          376320 non-null  int64
 2   entidad            376320 non-null  object
 3   tipo_de_delito     376320 non-null  object
 4   subtipo_de_delito  376320 non-null  object
 5   modalidad          376320 non-null  object
 6   nombre_mes         376320 non-null  object
 7   frecuencia         357504 non-null  float64
dtypes: float64(1), int64(2), object(5)
memory usage: 23.0+ MB

Supongamos que para este análisis, no nos importan los niveles subtipo de delito y modalidad. O sea, no queremos tener la distinción entre homicidios dolosos y culposos (sé que son bastante diferentes, pero simplifiquemos nuestro ejemplo).

Vamos a agrupar nuestro dataframe por anio, clave_ent, entidad, tipo_de_delito y nombre_mes. Esto hará que todos los tipos de homicidios se sumen al tipo "homicidio" o todos los tipos de robo de vehículo (con o sin violencia) se sumen a "robo de vehículo".

In [108]:
datos_long = datos_long.groupby(['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'nombre_mes'])['frecuencia'].sum().reset_index()

In [109]:
datos_long[datos_long.tipo_de_delito == 'Robo'].sample(15)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia
11908,2015,25,Sinaloa,Robo,febrero,952.0
54624,2018,18,Nayarit,Robo,abril,112.0
58468,2018,26,Sonora,Robo,febrero,615.0
14793,2015,31,Yucatán,Robo,noviembre,333.0
114144,2022,14,Jalisco,Robo,abril,3668.0
121355,2022,29,Tlaxcala,Robo,septiembre,236.0
84868,2020,17,Morelos,Robo,febrero,1349.0
29184,2016,29,Tlaxcala,Robo,abril,408.0
126634,2023,8,Chihuahua,Robo,octubre,1324.0
137195,2023,30,Veracruz de Ignacio de la Llave,Robo,septiembre,1526.0
31107,2017,1,Aguascalientes,Robo,enero,1126.0
153028,2024,31,Yucatán,Robo,febrero,34.0
88713,2020,25,Sinaloa,Robo,noviembre,618.0
69515,2019,17,Morelos,Robo,septiembre,1380.0
102634,2021,22,Querétaro,Robo,octubre,1902.0

Mostremos todos los estados y su respectiva clave

In [110]:
datos_long[['clave_ent', 'entidad']].drop_duplicates().sort_values('entidad')

       clave_ent                          entidad
0              1                   Aguascalientes
480            2                  Baja California
960            3              Baja California Sur
1440           4                         Campeche
2880           7                          Chiapas
3360           8                        Chihuahua
3840           9                 Ciudad de México
1920           5             Coahuila de Zaragoza
2400           6                           Colima
4320          10                          Durango
4800          11                       Guanajuato
5280          12                         Guerrero
5760          13                          Hidalgo
6240          14                          Jalisco
7200          16              Michoacán de Ocampo
7680          17                          Morelos
6720          15                           México
8160          18                          Nayarit
8640          19                       Nuevo León
9120          20                           Oaxaca
9600          21                           Puebla
10080         22                        Querétaro
10560         23                     Quintana Roo
11040         24                  San Luis Potosí
11520         25                          Sinaloa
12000         26                           Sonora
12480         27                          Tabasco
12960         28                       Tamaulipas
13440         29                         Tlaxcala
13920         30  Veracruz de Ignacio de la Llave
14400         31                          Yucatán
14880         32                        Zacatecas

Ahora Veamos todos los datos de delitos de una entidad en específico. Por ejemplo, Nuevo león

In [111]:
datos_long[datos_long['clave_ent'] == 19].sample(15)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia
85761,2020,19,Nuevo León,Otros delitos contra la sociedad,noviembre,0.0
39792,2017,19,Nuevo León,Violación equiparada,abril,18.0
54723,2018,19,Nuevo León,Aborto,enero,3.0
147174,2024,19,Nuevo León,Otros delitos contra el patrimonio,junio,9.0
54842,2018,19,Nuevo León,Despojo,diciembre,51.0
8929,2015,19,Nuevo León,Otros delitos contra el patrimonio,agosto,4.0
131592,2023,19,Nuevo León,Contra el medio ambiente,abril,6.0
39452,2017,19,Nuevo León,Corrupción de menores,mayo,17.0
101021,2021,19,Nuevo León,Homicidio,julio,149.0
8874,2015,19,Nuevo León,Hostigamiento sexual,junio,4.0
24455,2016,19,Nuevo León,Violación simple,septiembre,68.0
70141,2019,19,Nuevo León,Amenazas,agosto,340.0
131717,2023,19,Nuevo León,Feminicidio,julio,4.0
85750,2020,19,Nuevo León,Otros delitos contra la familia,octubre,485.0
70154,2019,19,Nuevo León,Contra el medio ambiente,diciembre,0.0

In [112]:
datos_long[(datos_long['clave_ent'] > 19) &  (datos_long['clave_ent'] < 24) & (datos_long['tipo_de_delito'] == 'Homicidio')].sample(15)

        anio  clave_ent       entidad tipo_de_delito  nombre_mes  frecuencia
41499   2017         23  Quintana Roo      Homicidio       enero        29.0
41016   2017         22     Querétaro      Homicidio       abril        51.0
87098   2020         22     Querétaro      Homicidio   diciembre        32.0
132218  2023         20        Oaxaca      Homicidio   diciembre       158.0
133187  2023         22     Querétaro      Homicidio  septiembre        37.0
10301   2015         22     Querétaro      Homicidio       julio        36.0
9826    2015         21        Puebla      Homicidio     octubre       122.0
117344  2022         21        Puebla      Homicidio        mayo       129.0
72216   2019         23  Quintana Roo      Homicidio       abril       136.0
24698   2016         20        Oaxaca      Homicidio   diciembre       162.0
87586   2020         23  Quintana Roo      Homicidio     octubre       106.0
9825    2015         21        Puebla      Homicidio   noviembre       100.0
10298   2015         22     Querétaro      Homicidio   diciembre        42.0
25181   2016         21        Puebla      Homicidio       julio       106.0
87103   2020         22     Querétaro      Homicidio       marzo        49.0

### Valores de fechas

Finalmente, queremos tener una columna "fecha". Actualmente tenemos el año y el nombre del mes, pero no tenemos como tal una columna que tenga un tipo de dato fecha. Eso hace que filtrar por fecha sea complicado.

Por ejemplo, si queremos conocer todos los homicidios de Oaxaca en enero 2024, haríamos lo siguiente:

In [113]:
datos_long[
    (datos_long['clave_ent'] == 20) &
    (datos_long['tipo_de_delito'] == 'Homicidio') &
    (datos_long['anio'] == 2024) &
    (datos_long['nombre_mes'] == 'enero')
]

        anio  clave_ent entidad tipo_de_delito nombre_mes  frecuencia
147579  2024         20  Oaxaca      Homicidio      enero       157.0

Creemos una columna de fecha.

Primero tenemos que convertir el nombre de mes a un número, en donde 1 es enero, 2 febrero, etc.

In [114]:
datos_long.sample(2)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia
75098,2019,29,Tlaxcala,Homicidio,diciembre,15.0
124667,2023,4,Campeche,Otros delitos que atentan contra la libertad p...,septiembre,25.0

In [115]:
datos_long["nueva_columna"] = "dato vacío"
datos_long.sample(6)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna
6155,2015,13,Hidalgo,Robo,septiembre,1015.0,dato vacío
24798,2016,20,Oaxaca,Otros delitos contra la sociedad,junio,33.0,dato vacío
107230,2021,32,Zacatecas,Falsificación,octubre,12.0,dato vacío
45477,2017,31,Yucatán,Otros delitos que atentan contra la libertad y...,noviembre,2.0,dato vacío
47111,2018,3,Baja California Sur,Amenazas,septiembre,121.0,dato vacío
50383,2018,9,Ciudad de México,Violencia de género en todas sus modalidades d...,marzo,0.0,dato vacío

In [116]:
# Diccionario de ayuda para convertir
meses = {
    "enero": 1,
    "febrero": 2,
    "marzo": 3,
    "abril": 4,
    "mayo": 5,
    "junio": 6,
    "julio": 7,
    "agosto": 8,
    "septiembre": 9,
    "octubre": 10,
    "noviembre": 11,
    "diciembre": 12
}

datos_long['mes'] = datos_long['nombre_mes'].map(meses)
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes
93849,2021,4,Campeche,Incesto,noviembre,0.0,dato vacío,11
75201,2019,29,Tlaxcala,Otros delitos contra la sociedad,noviembre,0.0,dato vacío,11
61311,2018,32,Zacatecas,Otros delitos que atentan contra la libertad y...,enero,4.0,dato vacío,1
137303,2023,31,Yucatán,Abuso de confianza,septiembre,9.0,dato vacío,9
88488,2020,25,Sinaloa,Falsedad,abril,1.0,dato vacío,4

In [117]:
datos_long["frecuencia_mas_10"] = datos_long["frecuencia"] + 10
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10
79954,2020,7,Chiapas,Lesiones,octubre,107.0,dato vacío,10,117.0
98394,2021,13,Hidalgo,Violencia familiar,junio,579.0,dato vacío,6,589.0
82997,2020,13,Hidalgo,Violación equiparada,julio,29.0,dato vacío,7,39.0
61168,2018,32,Zacatecas,Fraude,febrero,81.0,dato vacío,2,91.0
44823,2017,30,Veracruz de Ignacio de la Llave,Falsificación,enero,32.0,dato vacío,1,42.0

In [118]:
datos_long["anio_mes"] = datos_long["anio"].astype(str) + datos_long["mes"].astype(str)
datos_long.sample(6)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10,anio_mes
92617,2021,1,Aguascalientes,Violencia de género en todas sus modalidades d...,agosto,0.0,dato vacío,8,10.0,20218
71328,2019,21,Puebla,Otros delitos contra el patrimonio,abril,0.0,dato vacío,4,10.0,20194
248,2015,1,Aguascalientes,Incesto,mayo,0.0,dato vacío,5,10.0,20155
92520,2021,1,Aguascalientes,Otros delitos que atentan contra la vida y la ...,abril,6.0,dato vacío,4,16.0,20214
35403,2017,10,Durango,Otros delitos que atentan contra la vida y la ...,enero,2.0,dato vacío,1,12.0,20171
104777,2021,27,Tabasco,Electorales,julio,2.0,dato vacío,7,12.0,20217

In [119]:
# yyyy-mm-dd, yy-mm-dd, yymmdd, yyyy/dd/mm

In [120]:
# Agregamos la columna de fecha juntando el año y el mes
datos_long['fecha'] = pd.to_datetime(datos_long['anio'].astype(str) + datos_long['mes'].astype(str), format='%Y%m')
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10,anio_mes,fecha
105746,2021,29,Tlaxcala,Evasión de presos,diciembre,0.0,dato vacío,12,10.0,202112,2021-12-01
49968,2018,9,Ciudad de México,Allanamiento de morada,abril,77.0,dato vacío,4,87.0,20184,2018-04-01
110654,2022,7,Chiapas,Incumplimiento de obligaciones de asistencia f...,diciembre,9.0,dato vacío,12,19.0,202212,2022-12-01
151457,2024,28,Tamaulipas,Incumplimiento de obligaciones de asistencia f...,julio,0.0,dato vacío,7,10.0,20247,2024-07-01
79692,2020,7,Chiapas,Abuso de confianza,abril,5.0,dato vacío,4,15.0,20204,2020-04-01

In [121]:
# Eliminamos las columnas que ya no necesitamos
datos_long = datos_long.drop(columns=['nueva_columna'])
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,mes,frecuencia_mas_10,anio_mes,fecha
137928,2023,32,Zacatecas,Falsedad,abril,25.0,4,35.0,20234,2023-04-01
7649,2015,16,Michoacán de Ocampo,Violación simple,julio,28.0,7,38.0,20157,2015-07-01
42876,2017,26,Sonora,Extorsión,abril,3.0,4,13.0,20174,2017-04-01
34498,2017,8,Chihuahua,Trata de personas,octubre,1.0,10,11.0,201710,2017-10-01
115270,2022,17,Morelos,Amenazas,octubre,463.0,10,473.0,202210,2022-10-01

Veamos los homicidios en oaxaca de enero 2024 a la fecha

In [122]:
datos_long[
    (datos_long.tipo_de_delito == "Homicidio") &
    (datos_long.clave_ent == 20) &
    (datos_long.fecha >= '2024-01-01')
].sort_values('fecha')

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,mes,frecuencia_mas_10,anio_mes,fecha
147579,2024,20,Oaxaca,Homicidio,enero,157.0,1,167.0,20241,2024-01-01
147580,2024,20,Oaxaca,Homicidio,febrero,170.0,2,180.0,20242,2024-02-01
147583,2024,20,Oaxaca,Homicidio,marzo,190.0,3,200.0,20243,2024-03-01
147576,2024,20,Oaxaca,Homicidio,abril,208.0,4,218.0,20244,2024-04-01
147584,2024,20,Oaxaca,Homicidio,mayo,236.0,5,246.0,20245,2024-05-01
147582,2024,20,Oaxaca,Homicidio,junio,202.0,6,212.0,20246,2024-06-01
147581,2024,20,Oaxaca,Homicidio,julio,0.0,7,10.0,20247,2024-07-01
147577,2024,20,Oaxaca,Homicidio,agosto,0.0,8,10.0,20248,2024-08-01
147587,2024,20,Oaxaca,Homicidio,septiembre,0.0,9,10.0,20249,2024-09-01
147586,2024,20,Oaxaca,Homicidio,octubre,0.0,10,10.0,202410,2024-10-01
147585,2024,20,Oaxaca,Homicidio,noviembre,0.0,11,10.0,202411,2024-11-01
147578,2024,20,Oaxaca,Homicidio,diciembre,0.0,12,10.0,202412,2024-12-01

In [123]:
datos_finales = datos_long[['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'nombre_mes', 'fecha', 'frecuencia']]
datos_finales.head(2)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,fecha,frecuencia
0,2015,1,Aguascalientes,Aborto,abril,2015-04-01,0.0
1,2015,1,Aguascalientes,Aborto,agosto,2015-08-01,0.0

Ya que tenemos muestros datos bien estructurados, los podemos guardar en nuestra computadora. Los guardaremos con el nombre "delitos.csv"

In [124]:
datos_finales.to_csv('data/delitos.csv', index=False)